name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '15 4 * * 0'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      build-date: ${{ steps.set-build-date.outputs.build-date }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-build-date
        run: echo "build-date=$(echo $(date -u "+%Y%m%dT%H%M%SZ"))" >> $GITHUB_OUTPUT

      - id: set-matrix
        run: |
          JSON=$(echo $(cat .github/workflows/php-matrix.json))
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile

  build-test:
    name: Docker Build Test
    needs: setup
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        versions: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            DEBIAN_CODENAME=${{ matrix.versions.debian_codename }}
            PHP_PACKAGES=${{ matrix.versions.php_packages }}
          tags: |
            php-cli:${{ matrix.versions.php_version }}

      - name: Run image
        id: run-image
        run: >
          echo "php-version=$(docker run -t php-cli:${{ matrix.versions.php_version }} | grep ^PHP | cut -d' ' -f2)" >> $GITHUB_OUTPUT

      - name: Test container output
        if: contains(steps.run-image.outputs.php-version, matrix.versions.php_version) == 'false'
        run: exit 1

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [setup, build-test]
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        versions: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            DEBIAN_CODENAME=${{ matrix.versions.debian_codename }}
            PHP_PACKAGES=${{ matrix.versions.php_packages }}
          tags: |
            genv/php-cli:${{ matrix.versions.php_version }}
            genv/php-cli:${{ matrix.versions.php_version }}-${{ needs.setup.outputs.build-date }}
            genv/php-cli:latest
